version: '3.8'

services:
  db:
    image: postgres:15
    container_name: production_stock_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: production_stock
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./app
    container_name: production_stock_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/production_stock
      - STRICT_DB=1
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: production_stock_web
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data: